"""profile, 2fa, settings; drop email_verified

Revision ID: 2c95a6241766
Revises: 894d8c0a60c4
Create Date: 2026-07-13 03:23:24.225049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c95a6241766'
down_revision = '894d8c0a60c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), server_default='', nullable=False))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('name')

    op.drop_table('settings')
    # ### end Alembic commands ###
