"""score metadata + midi

Revision ID: 3b798955f39a
Revises: 2c95a6241766
Create Date: 2026-07-13 03:33:27.634550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b798955f39a'
down_revision = '2c95a6241766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composer', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('arranger', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('has_midi', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('has_midi')
        batch_op.drop_column('arranger')
        batch_op.drop_column('composer')

    # ### end Alembic commands ###
