"""scores

Revision ID: 6386da0a86b8
Revises: 7cc9edde4544
Create Date: 2026-07-13 02:25:28.800330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6386da0a86b8'
down_revision = '7cc9edde4544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instrument', sa.String(length=40), nullable=False),
    sa.Column('stored_uuid', sa.String(length=32), nullable=False),
    sa.Column('has_pdf', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_uuid')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_user_id'))

    op.drop_table('scores')
    # ### end Alembic commands ###
