"""job work_dir

Revision ID: bf2afc9eee93
Revises: c47fde32ed13
Create Date: 2026-07-13 02:46:19.005097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2afc9eee93'
down_revision = 'c47fde32ed13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_dir', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('work_dir')

    # ### end Alembic commands ###
